

SELECT
    CAST("NU_ANO_CENSO" AS INT) AS "ANO",
    CAST("CO_MUNICIPIO_IES" AS INT) AS "FK_MUNICIPIO_CODIGO",
    SUM("QT_DOC_EX_MEST") AS "QT_DOC_EX_MEST",
    SUM("QT_DOC_EX_DOUT") AS "QT_DOC_EX_DOUT",
    SUM("QT_DOC_EXE") AS "QT_DOC_EXE"
FROM (
    
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2014"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2015"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2016"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2017"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2018"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2019"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2020"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2021"
    
    UNION ALL
   
   
    SELECT "NU_ANO_CENSO", "CO_MUNICIPIO_IES", "QT_DOC_EX_MEST", "QT_DOC_EX_DOUT", "QT_DOC_EXE"
    FROM "postgres"."raw"."DIM_EDUC_SUP_IES_2022"
    
   
) AS educ_sup_13
GROUP BY "NU_ANO_CENSO", "CO_MUNICIPIO_IES"
ORDER BY "ANO", "FK_MUNICIPIO_CODIGO"