WITH TB AS (
SELECT
  *
FROM "postgres"."raw"."DIM_ESTIMATIVA_DA_POPULACAO_POR_ANO_MUNICIPIO_IDADE" as "pop"
),

TB_ADD_FAIXA_IDADE AS (
SELECT
    TB."ANO" as "ANO",
    TB."ESTADO_CODIGO" as "FK_ESTADO_CODIGO",
    TB."MUNICIPIO_CODIGO" as "FK_MUNICIPIO_CODIGO",
    TB."QUANTIDADE_ESTIMADA" as "QUANTIDADE_ESTIMADA",
    CASE
        WHEN TB."IDADE" BETWEEN 0 AND 3 THEN '1'
        WHEN TB."IDADE" BETWEEN 4 AND 5 THEN '2'
        WHEN TB."IDADE" BETWEEN 6 AND 10 THEN '3'
        WHEN TB."IDADE" BETWEEN 11 AND 14 THEN '4'
        WHEN TB."IDADE" BETWEEN 15 AND 17 THEN '5'
        WHEN TB."IDADE" BETWEEN 18 AND 24 THEN '6'
        WHEN TB."IDADE" BETWEEN 25 AND 29 THEN '7'
        WHEN TB."IDADE" BETWEEN 30 AND 40 THEN '8'
        WHEN TB."IDADE" BETWEEN 41 AND 50 THEN '9'
        WHEN TB."IDADE" BETWEEN 51 AND 64 THEN '10'
        ELSE '11'
    END AS "FK_FAIXAS_ETARIAS_ID"
FROM
    TB),

ESTIMATIVA_POP AS (
SELECT
    CAST("ANO" AS INT),
    CAST("FK_ESTADO_CODIGO" AS INT),
    CAST("FK_MUNICIPIO_CODIGO" AS INT),
    CAST("FK_FAIXAS_ETARIAS_ID" AS INT),
    CAST(ROUND(SUM("QUANTIDADE_ESTIMADA")) AS INT) AS "QUANTIDADE_ESTIMADA"
FROM
    TB_ADD_FAIXA_IDADE
GROUP BY
    "FK_FAIXAS_ETARIAS_ID",
    "ANO",
    "FK_ESTADO_CODIGO",
    "FK_MUNICIPIO_CODIGO"
)
SELECT * FROM ESTIMATIVA_POP